Ergänze conditionsOfAccess (#91)
dini-ag-kim/amb pull request #124
Opened 2022-01-19 11:28 UTC by TobiasNx

2022-01-27 09:43 UTC, acka47 requested changes
Es fehlen auch hier die Beispiele und die Anpassung der HTML-Spec. Außerdem hatten wir soweit ich weiß beschlossen, ein kontrolliertes Vokabular zu benutzen, in SKOS, das wir bei Bedarf erweitern können. Bisher ist nur eine `enum` im JSON Schema.

Ein eigenes Repo für ein so kleines Vokabular ist wahrscheinlich etwas Overkill. Mein Vorschlag: Wir legen ein Repo namens `value-lists` an, in das wir solche kleinen Vokabulare packen. Was meinen andere?

2022-01-28 11:06 UTC, kulla commented
> Ein eigenes Repo für ein so kleines Vokabular ist wahrscheinlich etwas Overkill. Mein Vorschlag: Wir legen ein Repo namens `value-lists` an, in das wir solche kleinen Vokabulare packen. Was meinen andere?

Generell finde ich es gut. Bei `conditionsOfAccess` könnte man eine Ausnahme machen. In https://schema.org/conditionsOfAccess heißt es: "This property [...] is expressed only in natural language."

Habe hierzu auch keine spezielle Meinung. Kann mich auch mit einer Vokabelliste anfreunden.

2022-02-08 14:54 UTC, acka47 commented
Wie heute besprochen, habe ich mit der Anlage des Vokabulars begonnen, siehe https://github.com/dini-ag-kim/value-lists/pull/2

2022-02-17 10:26 UTC, acka47 approved these changes
Das [Zugangsbedingugnen-Vokabular](https://w3id.org/kim/conditionsOfAccess/) ist veröffentlicht, Schema, Testadateien und Spec angepasst. Für mich ist das dann so in Ordnung. Evtl. kann allerdings die Spec  noch besser formuliert sein. Vielleicht hat ja jemand einen Vorschlag...

2022-02-17 10:26 UTC, acka47 commented
@TobiasNx schau doch bitte auch mal drauf, ob das jetzt alles so passt.

2022-02-17 13:21 UTC, acka47 commented
> macht es dann Sinn hier auf ein Array zu setzen?

Habe ich mich auch gefragt. Allerdings kommt ja höchstens soewas wie "Accessible without login + Login for additional features" dazu, d.h. auch perspektivisch wird in der Beschreibung einer Lernressource nur eine "condition" aus der Liste von "conditions" gewählt.

2022-02-21 08:58 UTC, sroertgen approved these changes

2022-02-21 10:47 UTC, merged