Add trailer
dini-ag-kim/amb pull request #158
Opened 2022-09-12 11:26 UTC by acka47

Resolves #155

2022-09-13 11:25 UTC, acka47 commented
Ich hätte gerne mindestens zwei Reviewer für diesen PR, der inhaltlich bereits im Treffen besprochen wurde. @sroertgen und @mirjan-hoffmann, wärt ihr dazu bereit?

2022-09-13 16:43 UTC, kulla requested changes
Some ideas to make the JSON specification more concrete

2022-09-13 16:43 UTC, kulla commented on draft/schemas/trailer.json
> +            "type": "string"
```suggestion
            "type": "string",
            "pattern": "\\w+\\/[\\w+]+",
```

2022-09-13 16:43 UTC, kulla commented on draft/schemas/trailer.json
> +            "pattern": "^\\d*$"
```suggestion
            "pattern": "^\\d+$"
```

2022-09-13 16:43 UTC, kulla commented on draft/schemas/trailer.json
> +            "type": "string"
```suggestion
            "type": "string",
            "pattern": "^[A-Fa-f0-9]{64}$"
```

2022-09-13 16:43 UTC, kulla commented on draft/schemas/trailer.json
> +            "pattern": "^\\d*$"
```suggestion
            "pattern": "^\\d+$"
```

2022-09-14 07:41 UTC, mirjan-hoffmann commented on draft/schemas/trailer.json
> +            "type": "string"
In https://www.iana.org/assignments/media-types/media-types.xml sind ja alle möglichen Werte aufgeführt. Ob man das nochmal durch ein Pattern absichert oder nicht ist mir eigentlich gleich. Jedenfalls, falls ein Pattern genutzt wird, so müssten im zweiten Teil noch ein paar mehr Sonderzeichen mit rein um zB `application/mpeg4-generic` oder `application/vnd.century-systems.tcp_stream` abzudecken. Soweit ich es überblicke, sollte `\\w+\\/[\\w+-._]+` alle Sonderzeichen abdecken.

2022-09-16 10:12 UTC, acka47 commented
Thanks for the review and suggestions for improvement, @mirjan-hoffmann & @kulla . I just copied the schema parts from the [`encoding` schema](https://github.com/dini-ag-kim/amb/blob/main/draft/schemas/encoding.json). I will incorporate your improvements and also add a commit to also add those improvements to the `encoding` schema.

2022-09-16 10:21 UTC, acka47 commented on draft/schemas/trailer.json
> +            "type": "string"
Diese Antwort auf Stack Overflow spricht sich gegen die Nutzung einer RegEx für IANA Meida Types aus: https://stackoverflow.com/questions/12663354/regular-expression-for-filetypes#12663541

[Wikidata](https://www.wikidata.org/wiki/Property:P1163#P1793) hingegen verwendet folgende RegEx: `(application|audio|example|font|image|message|model|multipart|text|video)/[a-zA-Z0-9\-+.]+`

Ich schlage vor, dass wir auch die Wikidata RegEx verwenden. Ok?

2022-09-16 10:51 UTC, mirjan-hoffmann commented on draft/schemas/trailer.json
> +            "type": "string"
Ok, sollte sich im Nachhinein herausstellen (was ich nicht glaube), dass in der Praxis doch noch weitere Typen verwendet werden, die hiermit nicht möglich sind, so kann dann immer noch nachgebessert werden.

2022-09-16 10:54 UTC, mirjan-hoffmann commented on draft/schemas/trailer.json
> +            "type": "string"
Ist es ein Problem, dass der Unterstrich `_` für zB `application/vnd.century-systems.tcp_stream` fehlt? Meiner Meinung nach werden die entsprechenden Werte vermutlich eh nirgends verwendet. Wollen wir ihn der Vollständigkeit halber dennoch aufnehmen?

2022-09-16 11:46 UTC, acka47 commented on draft/schemas/trailer.json
> +            "type": "string"
> Wollen wir ihn der Vollständigkeit halber dennoch aufnehmen?

Erledigt in [c9cfeeb](https://github.com/dini-ag-kim/amb/pull/158/commits/c9cfeeb1ae3d81bb25840fe2c3da80782d196528).

2022-09-16 12:05 UTC, mirjan-hoffmann approved these changes
+1

2022-09-22 13:44 UTC, acka47 commented
@kulla Kannst du bitte nochmal kurz draufschauen und grünes Licht geben, wenn dir nichts weiter auffällt?

2022-09-23 13:56 UTC, kulla approved these changes

2022-09-23 13:56 UTC, kulla commented
LGTM :+1:

2022-09-23 14:37 UTC, merged

2022-09-23 14:46 UTC, acka47 commented
Thanks for the review. Merged.